{:config {:order 0, :description "Tutorial Recording", :name :tutorial}
 :data
 [
  [:node-create [] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:value [:main :my-counter] nil 10]
  [:transform-enable [:main :my-counter] :inc [{:io.pedestal.app.messages/topic [:my-counter]}]]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 17]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 5.67]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 10]
  [:node-create [:main :counters] :map]
  [:value [:main :counters] nil {"abc" 3, "Me" 10, "xyz" 4}]
  [:node-create [:main :other-counters] :map]
  [:node-create [:main :other-counters "abc"] :map]
  [:value [:main :other-counters "abc"] nil 3]
  [:node-create [:main :other-counters "xyz"] :map]
  [:value [:main :other-counters "xyz"] nil 4]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 56]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 8]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 14]
  :break
  [:value [:main :total-count] 17 18]
  [:value [:main :average-count] 5.67 6]
  [:value [:main :max-count] 10 11]
  [:value [:main :my-counter] 10 11]
  [:value [:main :counters] {"abc" 3, "Me" 10, "xyz" 4} {"abc" 3, "Me" 11, "xyz" 4}]
  [:value [:pedestal :debug :dataflow-time] 8 10]
  :break
  [:value [:main :total-count] 18 19]
  [:value [:main :average-count] 6 6.33]
  [:value [:main :max-count] 11 12]
  [:value [:main :my-counter] 11 12]
  [:value [:main :counters] {"abc" 3, "Me" 11, "xyz" 4} {"abc" 3, "Me" 12, "xyz" 4}]
  [:value [:pedestal :debug :dataflow-time] 10 9]
  [:value [:pedestal :debug :dataflow-time-avg] 14 13]
  :break
  [:value [:main :total-count] 19 20]
  [:value [:main :average-count] 6.33 6.67]
  [:value [:main :max-count] 12 13]
  [:value [:main :my-counter] 12 13]
  [:value [:main :counters] {"abc" 3, "Me" 12, "xyz" 4} {"abc" 3, "Me" 13, "xyz" 4}]
  [:value [:pedestal :debug :dataflow-time] 9 8]
  :break
  [:value [:main :total-count] 20 21]
  [:value [:main :average-count] 6.67 7]
  [:value [:main :max-count] 13 14]
  [:value [:main :my-counter] 13 14]
  [:value [:main :counters] {"abc" 3, "Me" 13, "xyz" 4} {"abc" 3, "Me" 14, "xyz" 4}]
  [:value [:pedestal :debug :dataflow-time] 8 10]
  :break
  [:value [:main :total-count] 21 22]
  [:value [:main :average-count] 7 7.33]
  [:value [:main :max-count] 14 15]
  [:value [:main :my-counter] 14 15]
  [:value [:main :counters] {"abc" 3, "Me" 14, "xyz" 4} {"abc" 3, "Me" 15, "xyz" 4}]
  :break
  [:value [:main :total-count] 22 23]
  [:value [:main :average-count] 7.33 7.67]
  [:value [:main :max-count] 15 16]
  [:value [:main :my-counter] 15 16]
  [:value [:main :counters] {"abc" 3, "Me" 15, "xyz" 4} {"abc" 3, "Me" 16, "xyz" 4}]
  [:value [:pedestal :debug :dataflow-time] 10 8]
  :break
  [:value [:main :total-count] 23 24]
  [:value [:main :average-count] 7.67 8]
  [:value [:main :max-count] 16 17]
  [:value [:main :my-counter] 16 17]
  [:value [:main :counters] {"abc" 3, "Me" 16, "xyz" 4} {"abc" 3, "Me" 17, "xyz" 4}]
  :break
  [:value [:main :total-count] 24 25]
  [:value [:main :average-count] 8 8.33]
  [:value [:main :max-count] 17 18]
  [:value [:main :my-counter] 17 18]
  [:value [:main :counters] {"abc" 3, "Me" 17, "xyz" 4} {"abc" 3, "Me" 18, "xyz" 4}]
  :break
  [:value [:main :total-count] 25 26]
  [:value [:main :average-count] 8.33 8.67]
  [:value [:main :max-count] 18 19]
  [:value [:main :my-counter] 18 19]
  [:value [:main :counters] {"abc" 3, "Me" 18, "xyz" 4} {"abc" 3, "Me" 19, "xyz" 4}]
  :break
  [:value [:main :total-count] 26 27]
  [:value [:main :average-count] 8.67 9]
  [:value [:main :max-count] 19 20]
  [:value [:main :my-counter] 19 20]
  [:value [:main :counters] {"abc" 3, "Me" 19, "xyz" 4} {"abc" 3, "Me" 20, "xyz" 4}]
  [:value [:pedestal :debug :dataflow-time] 8 9]
  [:value [:pedestal :debug :dataflow-time-avg] 13 12]
  :break
  [:value [:main :total-count] 27 28]
  [:value [:main :average-count] 9 9.33]
  [:value [:main :max-count] 20 21]
  [:value [:main :my-counter] 20 21]
  [:value [:main :counters] {"abc" 3, "Me" 20, "xyz" 4} {"abc" 3, "Me" 21, "xyz" 4}]
 ]}